language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-M5

jdk:
  - oraclejdk8
  - oraclejdk9

script: sbt ++$TRAVIS_SCALA_VERSION test doc mimaReportBinaryIssues

before_cache:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
